# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username
patreon: PegasusHeavyIndustries
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift package name
# community_bridge: # Replace with your Community Bridge project slug
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# lfx_crowdfunding: # Replace with your LFX Crowdfunding project slug
# polar: # Replace with your Polar username
# custom: ['https://www.patreon.com/c/PegasusHeavyIndustries']

